- src/bin/cymba.rs
This add a very minimal binary to cymbalum, using the recent input module to setup the run. 
The main function should be expanded with a real interface and better error messages, but this is a starting point, allowing people to run simulations without writing code!
> Very minimal main function

- src/core/src/sim/mc/mod.rs
- src/core/src/sim/mc/monte_carlo.rs
- src/core/src/sim/mc/moves/mod.rs
- src/core/src/sim/mc/moves/rotate.rs
- src/core/src/sim/mc/moves/translate.rs
This implementation addresses issue #23 .
There is still work to do to make the changes work with the `lumol input` crate.
I'd appreciate feedback/critique/suggestions and questions.
> Implement feature: adjustable maximum displacement in Monte-Carlo

- Contributing.md
- README.md
This contains improvements for the language and update the build instructions for Lumol.
- [New README](https://github.com/lumol-org/lumol/blob/fcbd01120e275f3985815f48223dc287af9f81bf/README.md)
- [New contributor instructions](https://github.com/lumol-org/lumol/blob/fcbd01120e275f3985815f48223dc287af9f81bf/Contributing.md)
It also change the goals of the framework to be **flexible**, **reliable** and **extensible**. I did not put fast and parallel in them, because I want to wait for #49 verdict before saying so; and because the code is not yet parallel (see #56 for the discussion about this).
Do you agree with this set of goal? Am I missing something?
> Improve README and contributor documentation

- src/core/src/sys/cells.rs
@g-bauer noticed this and it was a quick refactor.
Now we use [to_degrees](https://doc.rust-lang.org/1.6.0/std/primitive.f64.html#method.to_degrees) and [to_radians](https://doc.rust-lang.org/1.6.0/std/primitive.f64.html#method.to_radians) to do that transformation instead of an inline function.
> Use f64 standard functions for angle conversion

- .travis.yml
- codecov.yml
Getting a 96% code coverage for the whole project in #66 is a bit suspicious, let's get a more accurate coverage.
DO NOT MERGE, this will probably need to update codecov.yml too.
> Link dead code for more accurate coverage generation

- src/core/src/sim/mc/monte_carlo.rs
- src/core/src/sim/mc/moves/mod.rs
- src/core/src/sim/mc/moves/rotate.rs
- src/core/src/sim/mc/moves/translate.rs
This PR adds a `setup` function for `MCMove`.
The interface is identical to the `setup` function for the `Integrator` trait:
```rust
fn setup(&mut self, system: &System) { ... }
```
This can be used to get information from the `System` before the simulation starts. For example, we can get the cutoff radius from the interaction potentials, which is useful to decide how much a cell can be resized or to limit the amplitude of translations.
For the currently implemented moves, `rotate` and `translate`, this function does nothing. For `translate` we might want to add a limitation for the translation range `dr` that can be set here.
> Add setup function for MCMove

- src/core/src/energy/pairs.rs
- src/core/src/sys/interactions.rs
- src/core/src/sys/systems.rs
This PR adds functionality to access the largest cutoff from all `pairs`. This is useful to get the limit of the smallest simulation cell.
Currently, only pair interactions are considered, no electrostatics.
> Add function to get the largest cutoff radius

- src/core/src/sys/cache.rs
This PR addresses two topics:
The bug was in the update closure [here](https://github.com/lumol-org/lumol/blob/12ebbf6379da4178eb4ca62a866a04f762979f18/src/core/src/sys/cache.rs#L245).
Imagine particle `i` moves away from particle `j` so that the old distance is `r_old < rc` and the new distance is `r_new > rc`. It's now at a distance larger than the cutoff which will lead to `energy_old != 0.0 -> energy_new = 0.0`. In the current state, this true energy will be skipped due to the if-clause. 
See [this](https://github.com/g-bauer/jupyter_notebooks/blob/master/cache_energy_debugged.ipynb) notebook for a simulation with the changes.
> Debug cache: move_particle_cost

- examples/data/simulation.toml
- examples/xenon.rs
* the `xenon` example did not use the correct trajectory file
* are the paths in the `toml` files supposed to be relative to the file ? If so I fixed them, if not we have a problem because these examples do not run
> Fix some examples

- .editorconfig
- Contributing.md
Ripped from the [crates.io repo](https://github.com/rust-lang/crates.io/blob/master/.editorconfig), this should add more consistency to the formatting (most editors support it), and in particular eliminate the "new line at the end of file" issue.
> Add .editorconfig file

- src/core/src/energy/global/mod.rs
- src/core/src/sim/mc/moves/resize.rs
- src/core/src/sys/cells.rs
- src/core/src/sys/compute.rs
- src/core/src/sys/energy.rs
- src/input/src/simulations/system.rs
Fix #89.
The first commit changes should not be controversial, as we assert that there are not reciprocal vectors and that tail correction does not make sense in infinite cells.
The second one is more open to discussion. When computing pressure/stress/virial, I set the volume to 1 and carry on with the computation.
TODO:
> Do not divide by zero when the cell in infinite

- doc/src/input/potentials.md
- src/core/src/energy/functions.rs
- src/core/src/energy/mod.rs
- src/core/src/units.rs
- src/input/src/interactions/pairs.rs
- src/input/src/interactions/toml.rs
- src/input/tests/interactions/bad/toml/born-1.toml
- src/input/tests/interactions/bad/toml/born-10.toml
- src/input/tests/interactions/bad/toml/born-11.toml
- src/input/tests/interactions/bad/toml/born-2.toml
- src/input/tests/interactions/bad/toml/born-3.toml
- src/input/tests/interactions/bad/toml/born-4.toml
- src/input/tests/interactions/bad/toml/born-5.toml
- src/input/tests/interactions/bad/toml/born-6.toml
- src/input/tests/interactions/bad/toml/born-7.toml
- src/input/tests/interactions/bad/toml/born-8.toml
- src/input/tests/interactions/bad/toml/born-9.toml
- src/input/tests/interactions/bad/toml/buckingham-1.toml
- src/input/tests/interactions/bad/toml/buckingham-2.toml
- src/input/tests/interactions/bad/toml/buckingham-3.toml
- src/input/tests/interactions/bad/toml/buckingham-4.toml
- src/input/tests/interactions/bad/toml/buckingham-5.toml
- src/input/tests/interactions/bad/toml/buckingham-6.toml
- src/input/tests/interactions/bad/toml/buckingham-7.toml
- src/input/tests/interactions/good/pairs.toml
This PR add the very common Buckingham potential, and the less common Born-Mayer-Huggins potential (derived from the Buckingham potential).
Two questions for the reviewers:
- I used the expressions from LAMMPS ([born](http://lammps.sandia.gov/doc/pair_born.html), [buckingham](http://lammps.sandia.gov/doc/pair_buck.html)), using `1/rho` instead of `B` in the exponential. [Wikipedia](https://en.wikipedia.org/wiki/Buckingham_potential) and [Sklog Wiki](http://www.sklogwiki.org/SklogWiki/index.php/Buckingham_potential) uses the other form. I prefer the one with rho because it make it clearer it is a length parameter. Is it OK for you?
- I used the `born` keyword in input instead of the verbose `Born-Mayer-Huggins`, is this OK? I am following LAMMPS here too.
Ref #6
> Add Buckingham and Born-Mayer-Huggins potentials

- src/core/src/energy/global/ewald.rs
Leads to a performance boost, on @Luthaf's machine:
``` bash
$ cargo benchcmp --threshold 4 before.log after.log 
name                            before.log ns/iter  after.log ns/iter  diff ns/iter   diff % 
cache_move_all_rigid_molecules  1,411,730           1,175,259              -236,471  -16.75% 
cache_move_particle             243,564             222,067                 -21,497   -8.83% 
cache_move_particle_ewald       393,670             494,358                 100,688   25.58% 
cache_move_particle_wolf        107,855             120,929                  13,074   12.12% 
cache_move_particles            273,819             374,547                 100,728   36.79% 
energy                          2,206,609           2,341,921               135,312    6.13% 
energy_ewald …
```
> Fix a threshold in the Ewald summation.

- src/core/src/energy/global/ewald.rs
- src/core/src/types/complex.rs
This PR introduces the following improvements:
1. in [`Ewald::kspace_force_factor`](https://github.com/lumol-org/lumol/blob/592e171cdbcc34f043f5653b347f97bfdf4e04c0/src/core/src/energy/global/ewald.rs#L416-L422) we perform some useless computations because we use only the imaginary part of a product between complex numbers, I introduced a method in the `Complex` class to change that.
2. I took the `expfactor` out of `Ewald::kspace_force_factor` because it is independent of `i` and `j`
3. I removed some redundant multplications
4. I moved the computation of `fourier_i` because it is independent of `j` 
Point 4. is the big hitter, it gives a 30% speedup. Point 2. also seems to have a big influence (but far less noticeable).
> Improve performance on the Ewald forces

- benches/argon.rs
- benches/nacl.rs
- benches/propane.rs
- benches/utils/mod.rs
- benches/water.rs
All is said in the title, this reduces the huge variability of cache benchmarks.
> Use fixed RNG seeds in benchmarks

- src/core/src/energy/global/ewald.rs
- src/core/src/energy/global/mod.rs
- src/core/src/energy/global/wolf.rs
- src/core/src/energy/pairs.rs
- src/core/src/sim/mc/moves/resize.rs
- src/core/src/sim/mc/moves/translate.rs
This PR adds a function to `GlobalPotentials`, that returns their `cutoff`.
In contrast to `PairPotentials`, `GlobalPotentials` may not have a cutoff so that the function returns an `Option`.
> Add function to get cutoff radius for global potentials.

- benches/nacl.rs
- benches/water.rs
- examples/mc_npt_spce.rs
- src/core/src/energy/global/ewald.rs
- src/core/src/energy/global/mod.rs
- src/core/src/energy/global/wolf.rs
- src/core/src/energy/mod.rs
- src/core/src/sys/cache.rs
- src/core/src/sys/compute.rs
- src/core/src/sys/energy.rs
- src/core/src/sys/interactions.rs
- src/input/src/interactions/coulomb.rs
- tests/nist-spce.rs
To make the System `Send + Sync` I applied the following changes:
1. the `GlobalPotential` trait now require `Send + Sync`;
2. methods of both `GlobalPotential` and `GlobalCache` take self by non-mutable reference;
This means that the System no longer has special knowledge of the global potentials and the RefCell are gone in Interactions.
This also means that we can not implement `CoulombicPotential` for Ewald right away, but we need to go through `struct SharedEwald(RwLock<Ewald>)` to get both interior mutability and Send + Sync.
@antoinewdg, in #131 you used `Arc<Mutex<_>>` for this, why the `Arc`?
> Make the System Sync + Send

- src/core/src/sim/mc/moves/resize.rs
- src/core/src/sys/interactions.rs
Adds checking of cutoffs (If present) from `GlobalPotential` within `setup` in the `Resize` MC move.
> Npt MC check global cutoff in setup function.

- benches/argon.rs
- benches/nacl.rs
- benches/propane.rs
- benches/utils/mod.rs
- benches/water.rs
This PR adds the current file name to the benchmark name for better readability of the output.
It also move all expensive setup to a lazy_static! macro, to try reducing the variability of benchmarks, but I am not totally convinced about this part.
The first two commits are to be discussed independently in #132.
The results are not really convincing, but I am sharing this to gather feedback.
```
argon::cache_move_particle                        169400 (+/- 54.85%)     221268 (+/- 43.01%) ∆ = -11.84%
argon::energy                                    2207974 (+/- 18.07%)    2031256 (+/- 42.66%) ∆ = +24.60%
argon::forces                                    2514489 (+/- 18.12%)    2492820 (+/- 20.65%) ∆ =  +2.53%
argon::virial                                    2894937 (+/- 16.04%)    3046181 …
```
> Some benchmarks improvements

- scripts/benchmark-pr.py
- scripts/requirements.txt
- scripts/run-benchmarks.py
This PR introduces a script that runs the benchmarks for a PR.
```
$ python scripts/run-benchmarks.py --help
Usage: run-benchmarks.py [OPTIONS] OUTPUT_DIR N_COMMITS PR_ID
Run the benchmarks for multiple commits on a PR and compare to master.
The benchmark results are saved in OUTPUT_DIR, and a comment with a
summary will be automatically added to the PR. This script requires the
environment variables LUMOL_GH_USERNAME and LUMOL_GH_TOKEN to contain
respectively the Github username and a personal access token.
Options:
--help  Show this message and exit.
```
After spending far too much time trying to design a script for this, I went with minimal functionality of running the benchmarks for a specific PR, for a specific number of commits.
(#139 comfirmed that benchmarks on Travis will not …
> Run benchmarks locally for a PR

- src/core/src/sim/mc/moves/rotate.rs
- src/core/src/types/matrix.rs
This PR moves the function `rotation_matrix` from the rotational MC move to be a method of `Matrix3` and adds a doctest.
I also modified the old function to compute the norm of `axis` inside the function.
> Adds rotation matrix as method of Matrix3.

- src/core/src/energy/global/ewald.rs
- src/core/src/types/matrix.rs
This PR:
* implements parallelization for `Ewald::kspace_virial`
* implements `std::iter::Sum<Matrix3>` for `Matrix3` so that we can use `sum` on the parallel iterators
I'm still fiddling with parallel iterators, so any suggestion is very welcome, especially about readability :).
> Parallelize Ewald::kspace_virial

- src/core/src/sys/composition.rs
- src/core/src/sys/compute.rs
- src/core/src/sys/energy.rs
- src/core/src/sys/mod.rs
- src/core/src/sys/systems.rs
We get O(1) composition retrivial, and no branching in energy and virial computation.
Also, the same bug as in #164 was present for virial: https://github.com/lumol-org/lumol/commit/88d3e9943ff78e14b37679007e2a410dc7e79ca0#diff-e3aff239f89d25b68f9bc977e87d49edL199
> Use a vector instead of a map for composition

- src/core/src/energy/global/ewald.rs
- src/core/src/parallel/prelude.rs
- src/core/src/parallel/shortcuts.rs
The previous implementation did not work because `ndarray::Zip` does not implement `rayon::IntoParallelIterator` but a custom `ndarray_parallel::NdarrayIntoParallelIterator`, this PR changes that.
Note that we had to roll back to implementing `Parallelhortcuts` only for `Range<T>` and not for all `T` that implements `IntoParallelIterator`.
> Implement ParallelShortcuts for ndarray::Zip

- benches/utils/mod.rs
- examples/binary.rs
- examples/mc_npt_argon.rs
- examples/mc_npt_ethane.rs
- examples/mc_npt_spce.rs
- examples/nacl.rs
- examples/xenon.rs
- src/core/src/out.rs
- src/core/src/sys/chfl.rs
- src/core/src/sys/mod.rs
- src/core/src/sys/system.rs
- src/core/src/utils/xyz.rs
- src/input/src/simulations/system.rs
- tests/nist-spce.rs
A bit of cleanup that allow to expose all the `chemfiles::Trajectory` options to users of lumol.
> Use the builder pattern for trajectories

- src/core/src/energy/global/ewald.rs
Simple change to avoid multiple access to a mutable reference and
instead use a stack value.
Improves the performance of density_fft by 40%.
> Speedup Ewald::density_fft

- src/core/src/energy/global/ewald.rs
- src/core/src/sim/mc/moves/resize.rs
- src/core/src/sys/cache.rs
- src/core/src/sys/chfl.rs
- src/core/src/sys/compute.rs
- src/core/src/sys/config/molecules.rs
- src/core/src/sys/config/particles.rs
- src/core/src/sys/energy.rs
- src/core/src/sys/mod.rs
- src/core/src/sys/system.rs
- src/core/src/types/matrix.rs
- src/input/src/interactions/angles.rs
- src/input/src/interactions/coulomb.rs
- src/input/src/interactions/mod.rs
- src/input/src/interactions/pairs.rs
- src/input/src/lib.rs
- src/input/src/simulations/logging.rs
- src/input/src/simulations/md.rs
- src/input/src/simulations/mod.rs
- src/input/src/simulations/outputs.rs
- src/input/src/simulations/propagator.rs
- src/input/src/simulations/simulations.rs
- src/input/src/simulations/system.rs
Now that rust 1.18 is out, we can use restricted privacy (`pub(crate)`), and remove a few todos from the code.
> Remove a few TODO from the code

- src/core/Cargo.toml
- src/core/src/energy/computations.rs
- src/core/src/energy/functions.rs
- src/core/src/energy/global/ewald.rs
- src/core/src/energy/global/mod.rs
- src/core/src/energy/global/wolf.rs
- src/core/src/energy/mod.rs
- src/core/src/energy/pairs.rs
- src/core/src/energy/restrictions.rs
- src/core/src/parallel/shortcuts.rs
- src/core/src/parallel/thread_local_store.rs
- src/core/src/sim/utils.rs
- src/core/src/sys/chfl.rs
- src/core/src/sys/config/composition.rs
- src/core/src/types/arrays.rs
- src/core/src/types/complex.rs
- src/core/src/types/matrix.rs
- src/core/src/types/vectors.rs
- src/core/src/units.rs
- src/input/src/lib.rs
- src/input/tests/input.rs
- src/lib.rs
It makes things confusing for external users how need to declare a dependency on lumol-core, but get to use extern crate lumol. Instead, add an actual lumol crate, re-exporting everything from lumol-core.
This allow to use the 'lumol' name both in dependencies and in extern crate.
> Do not use an alias lumol-core => lumol

- src/core/src/sim/md/controls.rs
- src/core/src/sys/veloc.rs
This prevent the flying ice-cube effect when the random velocity is not 100% isotropic
> Remove global translation and rotation on velocities initialization

- src/core/src/energy/computations.rs
- src/core/src/energy/functions.rs
- src/core/src/energy/global/ewald.rs
- src/core/src/energy/global/wolf.rs
- src/core/src/lib.rs
- src/core/src/math.rs
- src/core/src/sys/config/cells.rs
This PR introduces a new `math` module at the root of lumol-core, containing functions like `abs`, `cos`, `exp`, ... that will allow to use said functions directly without needing the `f64::` prefix.
> Cleanup of math heavy code

- .travis.yml
The code to find them was updated, but not the code to clean them from the Travis cache.
I was looking at the Travis logs from #196, and then I saw an error in the output: https://travis-ci.org/lumol-org/lumol/jobs/289677308#L5420-L5424. This should fix the error =)
> Update cleanup for cached tests executables

- .travis.yml
The previous code was deploying from both linux and OS X builders
> Only deploy docs to gh-pages once

- src/core/src/sim/mc/moves/translate.rs
This fixes a bug in `update_amplitude` where the warning was wrongfully emitted.
> Fix warning in MC move translate

- src/core/src/sim/mc/monte_carlo.rs
- src/core/src/sim/mc/moves/resize.rs
This PR adds:
- some small functions to eliminate "manual tracking" of counters
- fixes a small bug where acceptance was always printed (`info!`) as zero if no updates where performed
- enhances docs and tests for `MoveCounter`
> Some refactoring of the MoveCounter struct

- Cargo.toml
- src/bin/lumol.rs
- src/build.rs
- src/core/src/sim/mc/monte_carlo.rs
- src/input/src/simulations/logging.rs
- src/lib.rs
This is a few improvements on what is printed to the log during a simulation.
For example, the argon tutorial printed this before:
```
Logging to console as default.
You can configure logging in the [log] section of input file.
Monte Carlo simulation summary
Statistics for move: molecular translation
Attempts  : 100000
Acceptance: 67.8780 %
```
And now outputs this:
```
Printing logs to the console as default.
Running lumol version 0.1.0-1df7ad546
Simulation started the 2017-11-01 at 22:03:51
Monte Carlo simulation summary
molecular translation: 100000 attempts -- 67.9 % accepted
Simulation ended the 2017-11-01 at 22:03:54
Simulation ran for 0min 3s
```
> Improve what we print to the logs

- doc/src/conf.py
- scripts/ci/generate-docs.sh
Without it, github would not serve any file in a folder starting with _, which means that the book would not contains any JS or CSS
> Create a .nojekyll file at the root of gh-pages

- src/bin/lumol.rs
- src/input/src/lib.rs
- src/input/src/simulations/logging.rs
- src/input/src/simulations/mod.rs
Previously, the logger was not initialized if the input file was invalid, which resulted in error messages not being printed.
> Ensure that we also print error messages with invalid TOML files

- .travis.yml
- scripts/ci/install-travis.sh
- src/core/src/energy/global/ewald.rs
- src/core/src/energy/global/wolf.rs
- src/core/src/sys/config/cells.rs
- src/input/tests/input.rs
- tests/data/md-nacl/ewald-kspace.toml
- tests/data/md-nacl/nve-ewald-kspace.toml
- tests/md-nacl.rs
This PR contains a few fixes for bugs I found while working on #225.
While looking at the Ewald code, I found why @antoinewdg could not get a very good speedup when parallelizing Ewald: the real space code (which is ~50% of the time) was not parallel at all =) So the last commit in this PR uses Rayon to make the real space energy/forces/virial parallel.
> Ewald: fix and improve parallelization

- src/core/src/energy/global/ewald.rs
- src/core/src/energy/global/wolf.rs
- src/core/src/energy/pairs.rs
- src/core/src/sim/mc/moves/resize.rs
- src/core/src/sim/md/integrators.rs
- src/core/src/sys/cache.rs
- src/core/src/sys/config/cells.rs
- src/core/src/sys/system.rs
- src/input/tests/input.rs
- src/input/tests/simulation/good/system.toml
- tests/data/mc-water/ewald.toml
- tests/data/mc-water/wolf.toml
- tests/data/md-helium/npt-berendsen-barostat.toml
- tests/data/md-helium/nve-leap-frog.toml
- tests/data/md-helium/nve-perfect-gas.toml
- tests/data/md-helium/nve-shifted.toml
- tests/data/md-helium/nve-table.toml
- tests/data/md-helium/nve-velocity-verlet.toml
- tests/data/md-helium/nve-verlet.toml
- tests/data/md-nacl/ewald-kspace.toml
- tests/data/md-nacl/ewald.toml
- tests/data/md-nacl/wolf.toml
- tests/md-helium.rs
- tests/md-nacl.rs
- tutorials/potential/src/main.rs
Using potentials with a cutoff bigger than half the cell is not well defined with the current code, so this PR adds `fatal_error` in NPT MD integrator when resizing the cell to a small value, and when adding potentials to a system. 
NPT MC integrator already call `fatal_error`.
See #232 for initial discussion on this.
We could return `Result` instead of `panic!`ing  in `System::add_pair_potential`, but I am not really sure is it worth it: what could the user do with the Error case ?
> Error when using potentials with a too small cutoff 

- src/core/src/sys/compute.rs
- src/core/src/sys/config/composition.rs
- src/core/src/sys/config/configuration.rs
- src/core/src/sys/energy.rs
- src/core/src/sys/system.rs
We already know which particle kinds exist from the size of the composition, so there is no need for a separated function on `System`
> Add iteration on Composition, remove System::particle_kinds()

- doc/src/input/systems/interactions/electrostatic.rst
- src/core/src/energy/global/ewald.rs
- src/input/src/interactions/coulomb.rs
- src/input/src/interactions/mod.rs
- src/input/src/interactions/toml.rs
- src/input/src/lib.rs
- src/input/tests/interactions/bad/coulomb.toml
- src/input/tests/interactions/good/ewald.toml
The user should provide the cutoff and desired accuracy, and we compute optimal values for alpha and kmax from there. 
I took the algorithm to select alpha/kmax from LAMMPS.
Fix #183 
Fix #119
> Set Ewald parameters from a given precision

- benches/propane.rs
- benches/water.rs
- doc/requirements.txt
- examples/binary.rs
- examples/mc_npt_ethane.rs
- examples/mc_npt_spce.rs
- examples/xenon.rs
- src/core/Cargo.toml
- src/core/src/energy/global/ewald.rs
- src/core/src/energy/global/wolf.rs
- src/core/src/sim/mc/moves/mod.rs
- src/core/src/sim/mc/moves/resize.rs
- src/core/src/sim/mc/moves/rotate.rs
- src/core/src/sim/mc/moves/translate.rs
- src/core/src/sim/md/controls.rs
- src/core/src/sys/cache.rs
- src/core/src/sys/chfl.rs
- src/core/src/sys/compute.rs
- src/core/src/sys/config/bonding.rs
- src/core/src/sys/config/configuration.rs
- src/core/src/sys/config/mod.rs
- src/core/src/sys/config/molecules.rs
- src/core/src/sys/system.rs
- src/core/src/utils/xyz.rs
- src/input/src/simulations/mc.rs
- tests/md-butane.rs
- tests/md-methane.rs
This implement the end of #18, specifically the strategy in https://github.com/lumol-org/lumol/issues/18#issuecomment-268860305.
The idea is to have a real `Molecule` type, containing both bonding informations and particles. This means that functions needing particle information (center_of_mass, wrap, ...) can be implemented directly on the Molecule type.
Because the particles are stored in a SoA fashion inside the system, this also adds the `MoleculeRef` and `MoleculeRefMut` types, which are analogues to `&Molecule` and `&mut Molecule`, with data pointing inside a System.
> Better molecules type
