lumol-org/lumol

doc/src/SUMMARY.md
doc/src/input/interactions.md
doc/src/input/intro.md
doc/src/input/mc.md
doc/src/input/md.md
doc/src/input/potentials.md
doc/src/input/simulations.md
doc/src/input/systems.md
doc/src/input/units.md

This was long due. @g-bauer, do you have some time to give it a quick look?

Documentation for the input

---

src/core/src/simulation/mc/monte_carlo.rs
src/core/src/simulation/md/molecular_dynamics.rs
src/core/src/simulation/minimization/steepest_descent.rs
src/core/src/simulation/mod.rs
src/core/src/simulation/propagator.rs
src/core/src/simulation/simulations.rs
src/core/src/system/compute.rs
src/core/src/system/systems.rs
tests/mc-helium.rs

I went for an easy solution, asking the propagator for an external temperature strategy and using that for pressure/stress computations inside the system.

Pressure computation and Monte-Carlo

---

src/core/src/types/arrays.rs
src/core/src/types/complex.rs
src/core/src/types/matrix.rs
src/core/src/types/mod.rs
src/core/src/types/vectors.rs

Add examples to functions in the `types` module.
Ref #21

Doc examples

---

codecov.yml
src/core/src/sys/chfl.rs
src/core/src/sys/connect.rs
src/core/src/sys/mod.rs
src/core/src/sys/molecules.rs
src/core/src/sys/systems.rs

Simple refactoring of the molecule type and associated structs.

Refactor molecules

---

src/core/src/sys/systems.rs

A simple fix for #76: the assertion was documented but not checked by all the callers, I changed merge_molecule to reorder molid as it need.

Re-order molid before merging molecules

---

src/input/src/simulations/md.rs
src/input/tests/simulation/bad/md/controls-6.toml
src/input/tests/simulation/bad/md/controls-7.toml

Only accept integers as 'every' in controls

---

doc/src/input/potentials.md
src/input/src/interactions/pairs.rs

Only allow the lj key for Lennard-Jones input

---

doc/src/input/systems.md

Fix broken link

---

examples/mc_npt_ethane.rs
src/core/Cargo.toml
src/core/src/logging.rs
src/core/src/sys/cache.rs
src/core/src/sys/chfl.rs
src/input/Cargo.toml
src/input/src/extract.rs
src/input/src/simulations/system.rs

This release was hard to get out, but now I am back working on Lumol!

Update chemfiles to 0.7

---

Cargo.toml
LICENSE
codecov.yml
src/core/Cargo.toml
src/core/src/lib.rs
src/core/src/types/complex.rs
src/core/src/types/matrix.rs
src/core/src/types/vectors.rs
src/input/Cargo.toml
src/input/tests/input.rs
src/input/tests/interactions/bad/coulomb/coulomb-6.toml
src/input/tests/interactions/bad/coulomb/coulomb-7.toml
src/input/tests/interactions/bad/coulomb/coulomb-8.toml
src/input/tests/simulation/bad/md/thermostat-11.toml
src/input/tests/simulation/good/md-1.toml
src/input/tests/simulation/good/md-2.toml
src/input/tests/simulation/good/md-3.toml
src/input/tests/simulation/good/md-4.toml
src/input/tests/simulation/good/potentials.toml

The third clause is actually nice, especially in the context of scientific software.
Please check the box bellow if you agree:
I made this commits after running [cargo-lichking](https://github.com/Nemo157/cargo-lichking) on this repository. I would like to run the test on Travis, but it is currently failling because chemfiles is MPL. From my understanding, using MPL code inside other code is OK as long as the code is not modified. But this might be another argument to switch chemfiles to BSD (https://github.com/chemfiles/chemfiles/issues/48)

Update license to BSD-3-clauses

---

src/core/src/sim/simulations.rs

I had some simulations blowing up today, so I though this could be nice to have.
Remaining questions are:
1. should the checking interval be configurable by the user?
2. should we have a fully featured trait for this?
I think the answers are no and no, because (1) this should be transparent for the user (no setup required) and (2) it seems overkill (I can't think of a way someone would like to add other sanity checks from outside the core crate).
Both questions could also be addressed by (ab)using the `Output` trait for this, and maybe having 
some default output included with every simulation. They would need to be opt-out.

Add a sanity check for positions in the system

---

.travis.yml
doc/src/SUMMARY.md
doc/src/concepts/intro.md
doc/src/concepts/simulation.md
doc/src/faq.md
doc/src/input/interactions.md
doc/src/input/intro.md
doc/src/input/mc.md
doc/src/input/md.md
doc/src/installation.md
doc/src/intro.md
scripts/check-html-book.py

Fix #106 
Adding a script that does the job just for us is easy, we can replace it when mdbook win the ability to check internal links.
I am first checking that Travis does fails, I'll send another commit to fix broken links.

Check internal links on Travis

---

scripts/benchmark-pr.py

Simple modification of the benchmark script to allow for multiple PRs to be benchmarked.

Benchmark multiple PRs

---

src/core/Cargo.toml
src/core/src/lib.rs

I'm going to start breaking down #131 into smaller PRs to make reviews easier. This will be the starting point of all the PRs once merged.

Update dependencies for parallelization

---

src/core/src/sys/energy.rs

If a potential is defined for a non-existent particle kind, accessing the composition directly leads to a panic.

Fix: do not access missing particles kind composition

---

src/core/src/energy/global/wolf.rs
src/core/src/parallel/shortcuts.rs

This PR introduces simple parallelization of energy and virial computation in the Wolf summation method.

Parallelize wolf energy and virial

---

scripts/benchmark-pr.py

This was the reason the benchmark output was broken for me. The new script was used for https://github.com/lumol-org/lumol/pull/179#issuecomment-306816152.

Do not use color codes in commits sha

---

src/core/src/sys/compute.rs

Until now, we did not account for these, but we should ...
The angles and dihedrals contributions are zero as they only have an angular part, and no radial dependency. That's explained in the DL_POLY user manual.

Account for bond potential in virial calculations

---

benches/nacl.rs
benches/water.rs
src/core/src/energy/global/ewald.rs
src/core/src/energy/global/mod.rs
src/core/src/energy/global/wolf.rs
src/core/src/sys/compute.rs

Make force computations use mutable slices.

---

src/core/src/energy/functions.rs

https://github.com/lumol-org/lumol/issues/187

Remove inutile inline annotations

---

doc/src/input/potentials.md
src/core/src/energy/functions.rs
src/core/src/energy/mod.rs
src/input/src/interactions/angles.rs
src/input/src/interactions/pairs.rs
src/input/src/interactions/toml.rs
src/input/tests/interactions/bad/toml/morse-1.toml
src/input/tests/interactions/bad/toml/morse-2.toml
src/input/tests/interactions/bad/toml/morse-3.toml
src/input/tests/interactions/bad/toml/morse-4.toml
src/input/tests/interactions/bad/toml/morse-5.toml
src/input/tests/interactions/bad/toml/morse-6.toml
src/input/tests/interactions/good/angles.toml
src/input/tests/interactions/good/bonds.toml
src/input/tests/interactions/good/dihedrals.toml
src/input/tests/interactions/good/pairs.toml

So sorry guys, i had to recreate the same PR because I re-fork the project : PR#191
I have listened your feedbacks and i think it's now correct =)

Morse Potential implementation

---

doc/src/input/md.md
src/core/src/sim/md/controls.rs
src/core/src/sim/md/mod.rs
src/input/src/simulations/md.rs
src/input/tests/simulation/bad/md/controls-8.toml
src/input/tests/simulation/good/md-1.toml

Add a Rewrap control

---

src/core/src/energy/global/ewald.rs

This is based on @antoinewdg  work, and should replace #171 and #177. 
I did small adjustments in the cherry-picking process, but nothing performance sensitive. I am in favor of merging this even if the speedup is not optimal, as some speedup is better than nothing =)

Ewald parallel

---

doc/reference/systems/interactions/potentials.rst
src/core/src/energy/functions.rs
src/core/src/energy/mod.rs
src/input/src/interactions/pairs.rs
src/input/src/interactions/toml.rs
src/input/tests/interactions/bad/pairs/gaussian-1.toml
src/input/tests/interactions/good/pairs.toml

This PR is an implementation of a Gaussian potential.
Edit: Sorry for the formatting changes, this is due to `rustfmt` on save.

Implement Gaussian potential

---

src/core/src/sim/md/controls.rs
src/core/src/sim/md/integrators.rs
src/core/src/sys/compute.rs
src/core/src/sys/config/cells.rs
src/core/src/types/matrix.rs
src/core/src/types/vectors.rs

And use the implied Index implementation.

Implement Deref{Mut} for Vector3D and Matrix3D

---

benches/nacl.rs
benches/water.rs
examples/mc_npt_spce.rs
src/build.rs
src/core/src/energy/global/ewald.rs
src/input/src/interactions/toml.rs
tests/nist-spce.rs

This contains the trivial parts of #237, and the benchmark renaming.

Better benches

---

src/core/src/energy/global/ewald.rs

Both are pair interactions with a cutoff and thus can be computed together, saving a few computations of restriction informations / distances

Merge real space and molecular correction in Ewald

---

benches/argon.rs
benches/nacl.rs
benches/propane.rs
benches/water.rs
src/core/Cargo.toml
src/core/src/energy/global/ewald.rs
src/core/src/energy/global/mod.rs
src/core/src/energy/global/wolf.rs
src/core/src/sim/mc/moves/resize.rs
src/core/src/sim/mc/moves/rotate.rs
src/core/src/sim/mc/moves/translate.rs
src/core/src/sys/cache.rs
src/core/src/utils/xyz.rs

~The first commit it #250, I will rebase this PR when it is merged.~

 Change the cost evaluating functions to operate on rigid molecules 

---

src/core/src/sim/mc/mod.rs
src/core/src/sim/mc/monte_carlo.rs
src/core/src/sim/mc/moves/mod.rs
src/core/src/sim/mc/moves/resize.rs
src/core/src/sim/mc/moves/rotate.rs
src/core/src/sim/mc/moves/translate.rs
src/core/src/sim/md/molecular_dynamics.rs
src/core/src/sim/min/minimization.rs
src/core/src/sim/min/steepest_descent.rs
src/core/src/sim/mod.rs
src/core/src/sim/propagator.rs
src/core/src/sim/simulations.rs
src/core/src/sys/compute.rs
src/core/src/sys/config/composition.rs
src/core/src/sys/config/molecules.rs
src/core/src/sys/energy.rs
src/core/src/sys/system.rs

Here is my take on #79 !
~~The diff is pretty bad now, because this is based on #224. Once it is merged, I'll rebase here.~~
The idea here is to ask the propagator how many degrees of freedom are simulated, and then use this to compute the pressure/stress/temperature of the system.
This is marked as WIP because I want to add more MC tests using it and check that the original issue is actually solved.

Get the number of degrees of freedom from the propagator

---

Cargo.toml
examples/binary.rs
examples/xenon.rs
lumol-input/src/simulations/mc.rs
lumol-input/tests/simulation/bad/mc-update-frequency.toml
lumol-sim/src/mc/mod.rs
lumol-sim/src/mc/monte_carlo.rs
src/main.rs

Various small changes
